### ISSUE TITLE
LFS error

### ISSUE THREAD

**Issue by rezanazari** [wwbp/county_tweet_lexical_bank#1]
When trying to pull lfs files, I get an error:
 This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

I would like to use your csv/feat.cat_met_a30_2000_cp_w.msgs.cnty.1gra.csv
Is there any other way that I can download the file? e.g., through Google Drive, DropBox, Box, etc?

Thanks

**Comment by logan-life** [comment]
You can download the dataset [here](https://osf.io/zct2b/).

**Comment by sjgiorgi** [comment]
@logan-life That is actually different data. The data in the County Tweet Lexical bank is from a different time span and uses a different county aggregation method, one that is far superior to the paper data set you linked.  

@rezanazari Let me see if I can get this data into OSF. That might be easier than hosting here.

**Comment by logan-life** [comment]
My apologies!

**Comment by aamperalta** [comment]
Is it already on OSF?

**Comment by sjgiorgi** [comment]
The data is available through [Zenodo](https://doi.org/10.5281/zenodo.4895623).
